### ISSUE TITLE
USB-SD-Mux within regular SD card slot

### ISSUE THREAD

**Issue by sephalon** [linux-automation/usbsdmux#22]
I am aware that the [manual](https://testbed.linux-automation.com/usbsdmux-M01/intended-usecase.html) clearly states that

> The USB-SD-Mux is intended to be directly inserted into the SD card slot of a DUT.

However, we still have quite a lot of boards that only have regular SD card slots, but no microSD one. I did some experimentation and realized that

- a microSD to SD card adapter,
- a SanDisk Ultra microSD card and,
- deactivating high speed mode (`broken-mmc-highspeed` device tree property)

seems to be a reliable combination to use the USB-SD-Mux within a regular SD card slot.

However, this is a far from ideal situation with respect to ESD and reliability. Hence, I would like to ask if you have any plans to release an alternative USB-SD-Mux hardware version for regular SD card slots? Or do you have any other ideas how this scenario could be supported?

**Comment by SmithChart** [comment]
> I am aware that the [manual](https://testbed.linux-automation.com/usbsdmux-M01/intended-usecase.html) clearly states that
> 
> > The USB-SD-Mux is intended to be directly inserted into the SD card slot of a DUT.
> 
> However, we still have quite a lot of boards that only have regular SD card slots, but no microSD one.

Of course you are free to do what ever you want with your device. To be honest: we have a few devices in our lab where we need to use a adapter or an extension cable. The thing is: as a manufacturer we can not guarantee a good EMC-behavior in this cases. 

We currently have no plans to release such a USB-SD-Mux.

Thinking theoretically what would you want it to look like? Full-Size shape but with a Micro-SD socket or full-size shape with a full-size socket?

**Comment by sephalon** [comment]
> To be honest: we have a few devices in our lab where we need to use a adapter or an extension cable.

That is good to know :-) Would you like to share which combination of SD cards and adapter/extension cables are working well for you (also by private email if you do not want to put advertisements for specific manufacturers/products here)? Have been able to use higher speed modes with such a configuration?

> Thinking theoretically what would you want it to look like? Full-Size shape but with a Micro-SD socket or full-size shape with a full-size socket?

Full size shape with microSD socket. I do not see any benefit in having a full size socket, it would only make the USB-SD-Mux less versatile by increasing its size.

> Or do you have any other ideas how this scenario could be supported?

I do not know enough about PCB design to comment on that, but if it works, we would be interested too :-)

**Comment by SmithChart** [comment]
> That is good to know :-) Would you like to share which combination of SD cards and adapter/extension cables are working well for you (also by private email if you do not want to put advertisements for specific manufacturers/products here)? Have been able to use higher speed modes with such a configuration?

I will have a look around our lab what setups we are currently using.
If you drop me an E-Mail I can send you some products we are currently using.

> Full size shape with microSD socket. I do not see any benefit in having a full size socket, it would only make the USB-SD-Mux less versatile by increasing its size.

That is what I would suggest, too. In my understanding both cards are the same internally.

**Comment by sephalon** [comment]
> I will have a look around our lab what setups we are currently using.
> If you drop me an E-Mail I can send you some products we are currently using.

Thanks, dropped you an email.

I suggest we leave this issue open for further reference.

**Comment by SmithChart** [comment]
> I will have a look around our lab what setups we are currently using.
> If you drop me an E-Mail I can send you some products we are currently using.

I did a short survey through our lab.
I found: 12 Devices with Micro-SD-Slots, but only 4 devices with full-size SD-Slots.
The combinations of adapters and cards seems totally random. Most cards seem to be from Intenso (Class 4 and Class 10) though.
