### ISSUE TITLE
Missing validation of sg device path

### ISSUE THREAD

**Issue by lynxeye-dev** [linux-automation/usbsdmux#26]
While the comments in the code suggest that the device parameter should always point to a /dev/sg* there is no actual validation of the device path, so the utility will blindly run the ioctls against whatever path is given. While I have a hard time constructing a security issue out of a fixed set of ioctl calls, it certainly seems sloppy to not do any sanity checks.

I don't see any reason to allow paths outside of /dev, also validating that the given SG device is actually a usbsdmux seems appropriate as to not confuse unrelated SG devices with the usbsdmux specific ioctls if the user happens to specify the wrong device by accident or malice.

**Comment by hnez** [comment]
I've drafted a sg-device validation, but it was not received too well, as it relied on manually traversing the `/sys/devices` tree, which may break on other kernel versions.

Luckily we do not need the service/client slit anymore, so there is no longer an "ioctl oracle" available to any user that can access the service's control socket.
Access to USB-SD-Mux devices is now granted to normal users using `udev` rules that match only USB-SD-Muxes.
This is why I consider this issue closed, even though we have not implemented any checks in `usbsdmuxctl` itself.
