### ISSUE TITLE
Current drive??

### ISSUE THREAD

**Issue by akomakul** [linux-automation/usbsdmux#81]
Hi,
Could you please let me know how much current would drive the below pin in the image?

![image](https://github.com/linux-automation/usbsdmux/assets/172518115/79d38613-397a-4621-9eff-6b185bc926cd)

**Comment by akomakul** [comment]
Thanks for the reply.

Our device has 2 modes, flashing mode to update software via SD card and normal mode boots via eMMC.  We are connecting SD card to PC to write new image and then connect to DUT. After connecting to DUT we want to switch to flashing mode. For doing this we want to control the pin on the device using an extra GPIO pin on USB-SD-Mux but as such option is not available and as you have explained in https://github.com/linux-automation/usbsdmux/issues/49 we want to use the above mentioned pin.

**Comment by SmithChart** [comment]
OK, that sounds reasonable. Driving some logic level pin should be OK for this net. (As long as the open drain output + Pull-Up to 3.3V works for your DUT.)

**Comment by SmithChart** [comment]
Did not hear anything back from you. Closing this as solved for now. Feel free to open again.
