### ISSUE TITLE
Using multiple SDMuxes

### ISSUE THREAD

**Issue by Bozka222** [linux-automation/usbsdmux#82]
Hello, 
I have a problem with using two SDMux devices together. I am using server with Debian GNU/Linux 12 (bookworm). There is no problem with using one SDMux device but while I connect the second one to the server, first one disappears. This works back and forth so I can always see only one SDMux device. I can see both devices with command $ usb_devices but not with command $ ls -l /dev/usb-sd-mux nor with $ ls -l /dev/disk/by-id. While trying same configuration on ubuntu everything works as it should and I can see both devices connected.

![1](https://github.com/user-attachments/assets/210a6866-ef9b-4064-a93c-1d0004d7637d)
![2](https://github.com/user-attachments/assets/86354c5f-5d37-49cd-ae30-1dfc7aeabecb)
![3](https://github.com/user-attachments/assets/994f1636-8af0-4695-a70b-b0c0937f0c65)
![4](https://github.com/user-attachments/assets/a958ef25-bf6a-48ce-8538-d5988f230587)

**Comment by SmithChart** [comment]
In principal we expect multiple USB-SD-Mux on a single test server to work. This is taken from one of our test-servers:
```
cfi@rlabA-srv:~$ ls -lah /dev/usb-sd-mux/*
lrwxrwxrwx 1 root root 6 Sep  3 17:21 /dev/usb-sd-mux/id-000000000047 -> ../sg1
lrwxrwxrwx 1 root root 6 Sep 12 08:29 /dev/usb-sd-mux/id-000000000107 -> ../sg8
lrwxrwxrwx 1 root root 6 Sep  3 17:21 /dev/usb-sd-mux/id-000000000116 -> ../sg5
lrwxrwxrwx 1 root root 6 Sep  3 17:21 /dev/usb-sd-mux/id-000000000378 -> ../sg3
lrwxrwxrwx 1 root root 6 Sep 12 08:29 /dev/usb-sd-mux/id-000000000380 -> ../sg6
lrwxrwxrwx 1 root root 6 Sep  3 17:21 /dev/usb-sd-mux/id-000000000595 -> ../sg2
lrwxrwxrwx 1 root root 6 Sep  3 17:21 /dev/usb-sd-mux/id-000000001316 -> ../sg4
lrwxrwxrwx 1 root root 6 Sep 12 08:28 /dev/usb-sd-mux/id-000000001566 -> ../sg7
```

So this is definitely worth investigating.

What do you see in `dmesg -w` while plugging the first and then the second UBS-SD-Mux?

**Comment by Bozka222** [comment]
After plugging first SD-Mux:
![5](https://github.com/user-attachments/assets/62c2236e-8a32-4c62-bd6f-e9a7cc8ae39b)
and second SD-Mux:
![6](https://github.com/user-attachments/assets/9084a298-63ca-4b9d-9c27-8e7e50e8ec03)

**Comment by SmithChart** [comment]
Thanks. Each for itself looks OK: The only odd entry is the last line for the first sd-mux. 

Both devices use `/dev7sdb` and `/dev/sg1`, so assume there is something happening in between where these device nodes disappear?

**Comment by Bozka222** [comment]
Yes they both use `/dev/sg1` and `/dev/sdb`. Another strange thing I noticed now is that they need to be connected both together. When I connect only one, I do not see any SDMux devices connected. When i connect both I can see only the one device which I connected last.

**Comment by SmithChart** [comment]
What is happening inbetween? Can you provide the log? A `reset` should not be enough for the device to disappear. I would at least also suspect to see a `disconnect`.

**Comment by Bozka222** [comment]
Well, there is nothing between. 
![image](https://github.com/user-attachments/assets/5ef9654c-4321-4b1a-9d3d-73e23d1449de)

**Comment by Bozka222** [comment]
OK I found the root cause. I have connected one of the USB devices to my virtual machine in proxmox so that's why one of them was disappearing. Anyway thanks for the help.

**Comment by SmithChart** [comment]
Uh, that's an interesting effect. Good to hear if it works now.

I'll close this issue now. Feel free to reopen or open a new issue, if needed.

Cheers!
